### PR TITLE
minor improvements

### PR DESCRIPTION
**Pull request by rpalcolea**
Looping through all the methods is unnecessary. If we find a match, process the annotations and break the loop.

I think this could potentially impact the performance of your filter if the controller has a significant number of actions.

Also Use Logger to give users ability to manage levels and incorporate it with their log implementation: logback, log4j, etc.

Update: cleanup plugin config

### CODE REVIEW

**Comment by burtbeckwith** [comment]
I should pay more attention, I didn't see this and made many of the same changes in the PR I sent.

**Comment by rpalcolea** [comment]
No worries, definitely your changes are more accurate than mine. Hopefully @erickmorales3 will merge yours soon.

I'll close this commit since yours contains more changes/cleanup to the plugin.

**Comment by erickmorales3** [comment]
Hello @rpalcolea and @burtbeckwith,

I read all your comments and definitly your suggestions are very helpful. I am convinced that plugin will be better and faster. But I am actually checking minutely your commits because I think that the logical functionallity will affected. For example in case of enabling ActionLogging to all controller actions except to specific one, like this:   

``` java
@ActionLogging
class SampleController {

    def index(){

    }

    @ActionLogging(false)
    def methodWithoutActionLogging(){

    }
}
```

It should not store log event for methodWithoutActionLogging, but is doing it. #7 

So, I will checking all plugin functionalities with your suggestions and then I will publish an update. 

I hope this is useful for developers and Grails Comunity will aprove it soon

Thank you so much...

**Comment by burtbeckwith** [comment]
I think it's this around line 54:

```
if (!controllerClazz.getAnnotation(ActionLogging)?.value()) {
   return
}
```

When I first  starting working on the code I thought it would be good to return as early as possible from the filter minimize the cost of using it, but I wasn;t considering all of the possibilities that  are available.. Once I realized that the original logic was good I backed out this changes but missed that one.

**Pull request closed without merging**
